# Experimenting with Scrapy

In [1]:
import scrapy 
import time 
import sys, json 
import socket 
import requests 
import scrapy 
from scrapy.crawler import CrawlerProcess 


import requests 
from parsel import Selector

In [2]:
url = "https://quotes.toscrape.com/page/1/" 
html = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'}).text 
sel = Selector(text=html)

print("Artile title:", sel.xpath('//title/text()').get()) 
print("Artile title v2:", sel.css("title::text").get()) 

print("Quotes:", sel.css("span.text::text").getall())

Artile title: Quotes to Scrape
Artile title v2: Quotes to Scrape
Quotes: ['“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”', '“It is our choices, Harry, that show what we truly are, far more than our abilities.”', '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”', '“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”', "“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”", '“Try not to become a man of success. Rather become a man of value.”', '“It is better to be hated for what you are than to be loved for what you are not.”', "“I have not failed. I've just found 10,000 ways that won't work.”", "“A woman is like a tea bag; you never know how strong it is until it's in hot water.”", '“A day without sunshine is like, you know, night.”']

# A small test spider that gets a single page

In [3]:
import scrapy
import time 
import sys, json
import socket
import requests
import scrapy
from scrapy.crawler import CrawlerProcess

class SimpleSpider(scrapy.Spider):
    custom_settings = {
        "TWISTED_REACTOR": "twisted.internet.epollreactor.EPollReactor",
    }
    name = "my_spider"
    start_urls = ['https://quotes.toscrape.com/page/1/']  # Replace with the URL you want to fetch

    def parse(self, response):
        print("Page title:", response.xpath('//title/text()').get())
        print("Page title v2:", response.css('title::text').getall())
        print("Quotes:", response.css("span.text::text").getall())
        print("Authors:", response.css("small.author::text").getall())
        print("Tags:", response.css("a.tag::text").getall())
        for quote in response.css('div.quote'):
            print ('text:', quote.css('span.text::text').get(), 'author:', quote.css('small.author::text').get(), 'tags:', quote.css('div.tags a.tag::text').getall())
        print("Page raw html content:", response.text[:500])  # Print first 500 characters

# Run Scrapy inside Jupyter Notebook
process = CrawlerProcess(settings={
    "LOG_LEVEL": "WARN",  # Suppress logs
})
process.crawl(SimpleSpider)
process.start()

# Hungarian news spider

In [4]:
import scrapy
import time 
import sys, json
import socket
import requests
import scrapy
from scrapy.crawler import CrawlerProcess

class HungariannewsSpider(scrapy.Spider):
    custom_settings = {
        "TWISTED_REACTOR": "twisted.internet.epollreactor.EPollReactor",
    }
    name = 'telexhu'
    allowed_domains = ['telex.hu']
    start_urls = ['https://telex.hu/']

    def parse(self, response):
        #Extracting the content using xpath selectors
        title = response.css("div.title-section h1::text").extract()
        content = response.xpath("//div[@class='article-html-content']//text()").extract()


        yield {'url':response.url,'title':title,'content':content}


        #get links to follow
        for next_page in response.css("a::attr(href)").getall():
            if next_page is not None\
                    and not next_page.startswith('javascript')\
                    and not next_page.startswith('mailto'):
                next_page = response.urljoin(next_page)
                yield {'base_url':response.url, 'link':next_page}
                yield scrapy.Request(next_page, callback=self.parse)

In [5]:
import os
outfile = 'hungariannews.json'
if os.path.isfile(outfile):
    os.remove(outfile) 
    
process = CrawlerProcess(settings={
    #'LOG_LEVEL': 'WARN',  # Suppress logs, uncomment if you are ready
    'FEED_FORMAT': 'json', # jsonline is also useful
    'FEED_URI': outfile,
    'CLOSESPIDER_ITEMCOUNT': 1000, # Or stop by kernel interrupt
    'FEED_EXPORT_ENCODING': 'utf-8'
})
process.crawl(HungariannewsSpider)

process.start()

2026-03-21 11:06:46 [scrapy.utils.log] INFO: Scrapy 2.14.2 started (bot: scrapybot)
2026-03-21 11:06:46 [scrapy.utils.log] INFO: Versions:
{'lxml': '6.0.2',
 'libxml2': '2.14.6',
 'cssselect': '1.4.0',
 'parsel': '1.11.0',
 'w3lib': '2.4.1',
 'Twisted': '25.5.0',
 'Python': '3.14.3 (main, Feb  4 2026, 01:51:49) [Clang 21.1.4 ]',
 'pyOpenSSL': '26.0.0 (OpenSSL 3.5.5 27 Jan 2026)',
 'cryptography': '46.0.5',
 'Platform': 'macOS-15.1-arm64-arm-64bit-Mach-O'}
2026-03-21 11:06:46 [scrapy.crawler] DEBUG: Using CrawlerProcess
2026-03-21 11:06:46 [scrapy.addons] INFO: Enabled addons:
[]

In [6]:
import pandas as pd
alldata=pd.read_json(outfile)
alldata

Unhandled error in Deferred:
2026-03-21 11:06:46 [twisted] CRITICAL: Unhandled error in Deferred:
2026-03-21 11:06:46 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/defer.py", line 1853, in _inlineCallbacks
    result = context.run(
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/python/failure.py", line 467, in throwExceptionIntoGenerator
    return g.throw(self.value.with_traceback(self.tb))
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 423, in _crawl
    yield d
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/defer.py", line 1857, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 152, in crawl
    self._apply_settings()
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 112, in _apply_settings
    install_reactor(reactor_class, event_loop)
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/utils/reactor.py", line 112, in install_reactor
    reactor_class = load_object(reactor_path)
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/utils/misc.py", line 70, in load_object
    mod = import_module(module)
  File "/Users/tleo/.local/share/uv/python/cpython-3.14.3-macos-aarch64-none/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 759, in exec_module

  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed

  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/epollreactor.py", line 34, in <module>
    raise ImportError(e)
builtins.ImportError: module 'select' has no attribute 'epoll'

2026-03-21 11:06:46 [twisted] CRITICAL:
Traceback (most recent call last):
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/epollreactor.py", line 28, in <module>
    epoll = getattr(select, "epoll")
AttributeError: module 'select' has no attribute 'epoll'. Did you mean: 'poll'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/defer.py", line 1853, in _inlineCallbacks
    result = context.run(
        cast(Failure, result).throwExceptionIntoGenerator, gen
    )
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/python/failure.py", line 467, in throwExceptionIntoGenerator
    return g.throw(self.value.with_traceback(self.tb))
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 423, in _crawl
    yield d
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/defer.py", line 1857, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 152, in crawl
    self._apply_settings()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 112, in _apply_settings
    install_reactor(reactor_class, event_loop)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/utils/reactor.py", line 112, in install_reactor
    reactor_class = load_object(reactor_path)
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/utils/misc.py", line 70, in load_object
    mod = import_module(module)
  File "/Users/tleo/.local/share/uv/python/cpython-3.14.3-macos-aarch64-none/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/epollreactor.py", line 34, in <module>
    raise ImportError(e)
ImportError: module 'select' has no attribute 'epoll'
2026-03-21 11:06:46 [twisted] CRITICAL:
Traceback (most recent call last):
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/epollreactor.py", line 28, in <module>
    epoll = getattr(select, "epoll")
AttributeError: module 'select' has no attribute 'epoll'. Did you mean: 'poll'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/defer.py", line 1853, in _inlineCallbacks
    result = context.run(
        cast(Failure, result).throwExceptionIntoGenerator, gen
    )
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/python/failure.py", line 467, in throwExceptionIntoGenerator
    return g.throw(self.value.with_traceback(self.tb))
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 423, in _crawl
    yield d
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/defer.py", line 1857, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 152, in crawl
    self._apply_settings()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 112, in _apply_settings
    install_reactor(reactor_class, event_loop)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/utils/reactor.py", line 112, in install_reactor
    reactor_class = load_object(reactor_path)
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/utils/misc.py", line 70, in load_object
    mod = import_module(module)
  File "/Users/tleo/.local/share/uv/python/cpython-3.14.3-macos-aarch64-none/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/epollreactor.py", line 34, in <module>
    raise ImportError(e)
ImportError: module 'select' has no attribute 'epoll'
Unhandled error in Deferred:
2026-03-21 11:06:46 [twisted] CRITICAL: Unhandled error in Deferred:
2026-03-21 11:06:46 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/defer.py", line 1853, in _inlineCallbacks
    result = context.run(
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/python/failure.py", line 467, in throwExceptionIntoGenerator
    return g.throw(self.value.with_traceback(self.tb))
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 423, in _crawl
    yield d
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/defer.py", line 1857, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 152, in crawl
    self._apply_settings()
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 112, in _apply_settings
    install_reactor(reactor_class, event_loop)
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/utils/reactor.py", line 112, in install_reactor
    reactor_class = load_object(reactor_path)
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/utils/misc.py", line 70, in load_object
    mod = import_module(module)
  File "/Users/tleo/.local/share/uv/python/cpython-3.14.3-macos-aarch64-none/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 759, in exec_module

  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed

  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/epollreactor.py", line 34, in <module>
    raise ImportError(e)
builtins.ImportError: module 'select' has no attribute 'epoll'

2026-03-21 11:06:46 [twisted] CRITICAL:
Traceback (most recent call last):
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/epollreactor.py", line 28, in <module>
    epoll = getattr(select, "epoll")
AttributeError: module 'select' has no attribute 'epoll'. Did you mean: 'poll'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/defer.py", line 1853, in _inlineCallbacks
    result = context.run(
        cast(Failure, result).throwExceptionIntoGenerator, gen
    )
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/python/failure.py", line 467, in throwExceptionIntoGenerator
    return g.throw(self.value.with_traceback(self.tb))
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 423, in _crawl
    yield d
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/defer.py", line 1857, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 152, in crawl
    self._apply_settings()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 112, in _apply_settings
    install_reactor(reactor_class, event_loop)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/utils/reactor.py", line 112, in install_reactor
    reactor_class = load_object(reactor_path)
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/utils/misc.py", line 70, in load_object
    mod = import_module(module)
  File "/Users/tleo/.local/share/uv/python/cpython-3.14.3-macos-aarch64-none/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/epollreactor.py", line 34, in <module>
    raise ImportError(e)
ImportError: module 'select' has no attribute 'epoll'
2026-03-21 11:06:46 [twisted] CRITICAL:
Traceback (most recent call last):
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/epollreactor.py", line 28, in <module>
    epoll = getattr(select, "epoll")
AttributeError: module 'select' has no attribute 'epoll'. Did you mean: 'poll'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/defer.py", line 1853, in _inlineCallbacks
    result = context.run(
        cast(Failure, result).throwExceptionIntoGenerator, gen
    )
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/python/failure.py", line 467, in throwExceptionIntoGenerator
    return g.throw(self.value.with_traceback(self.tb))
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 423, in _crawl
    yield d
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/defer.py", line 1857, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 152, in crawl
    self._apply_settings()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/crawler.py", line 112, in _apply_settings
    install_reactor(reactor_class, event_loop)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/utils/reactor.py", line 112, in install_reactor
    reactor_class = load_object(reactor_path)
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/scrapy/utils/misc.py", line 70, in load_object
    mod = import_module(module)
  File "/Users/tleo/.local/share/uv/python/cpython-3.14.3-macos-aarch64-none/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/Users/tleo/Downloads/git/school/www/.venv/lib/python3.14/site-packages/twisted/internet/epollreactor.py", line 34, in <module>
    raise ImportError(e)
ImportError: module 'select' has no attribute 'epoll'

FileNotFoundError: File hungariannews.json does not exist

In [ ]:
links = alldata[alldata['base_url']==alldata['base_url']][['base_url','link']] # not NaN
links

               base_url                                    link
1     https://telex.hu/                       https://telex.hu/
2     https://telex.hu/                  https://telex.hu/after
3     https://telex.hu/                     https://telex.hu/g7
4     https://telex.hu/               https://telex.hu/karakter
5     https://telex.hu/              https://telex.hu/tamogatas
...                 ...                                     ...
3455  https://telex.hu/        https://www.facebook.com/telexhu
3456  https://telex.hu/  https://www.instagram.com/telexponthu/
3457  https://telex.hu/   https://www.youtube.com/c/telexponthu
3458  https://telex.hu/             https://twitter.com/telexhu
3459  https://telex.hu/                    https://telex.hu/rss

[3417 rows x 2 columns]

In [ ]:
news = alldata[alldata['url']==alldata['url']][['url','title','content']] # not NaN
news

,url,title,content
0,https://telex.hu/,[],[]
48,https://telex.hu/tamogatas,[],[]
69,https://telex.hu/legfrissebb,[],[]
75,https://telex.hu/karakter,[],[]
78,https://telex.hu/g7,[],[]
87,https://telex.hu/gazdasag/2026/03/09/nagy-mart...,"[Nagy Márton: Megtiltja a kormány a nyersolaj,...",[Az uniós minimumszintre csökkenti a kormány a...
112,https://telex.hu/after,[],[]
125,https://telex.hu/tamogatas/profil,[],[]
128,https://telex.hu/belfold/2026/03/09/ot-partlis...,"[Minden eddiginél kevesebb, csak öt párt listá...","[A rendszerváltás óta a legkevesebb, öt pártli..."
132,https://telex.hu/belfold/2026/03/09/buzas-habe...,[A Pécs Pride szervezőjének ügyét is felfügges...,[Hasonlóan döntött a Pécsi Járásbíróság a Prid...
136,https://telex.hu/kulfold/2026/03/09/kristi-noe...,"[„Soha ne tegyél keresztbe Trumpnak, soha ne h...",[Elkezdték fenni a késeket a Trump-adminisztrá...
138,https://telex.hu/,[],[]
167,https://telex.hu/after/2026/03/09/labubuk-a-sz...,[Kaotikus audiovizuális mix lett a magyar Labu...,[Szombat reggel fél 10-kor szokatlanul nagy vo...
168,https://telex.hu/rovat/gazdasag,[],[]
229,https://telex.hu/rovat/video,[],[]
230,https://telex.hu/szerzo/kersner-mate,[],[]
243,https://telex.hu/video/2026/03/09/nagy-ervin-t...,"[„Véresszájú fideszes voltam, de ebből teljese...",[Nagy Ervin szerint neki az csak előnyt jelent...
246,https://telex.hu/belfold/2026/03/09/horvath-lo...,[Az ukrán pénzszállítók ügyvédje szerint nem v...,"[A magyar állam a , hétfőn benyújtott törvényj..."
249,https://telex.hu/belfold/2026/03/09/lazar-jano...,[Lázár a lefoglalt ukrán pénzszállítmányról: N...,[A Lázárinfó helyébe lépett Lázárinfó Expressz...
269,https://telex.hu/rovat/belfold,[],[]
270,https://telex.hu/kulfold/2026/03/09/izrael-usa...,[Putyin máris megoldást vélt találni az energi...,"[A konfliktus miatt megugrottak az olajárak, a..."
294,https://shop.telex.hu,[],[]
409,https://telex.hu/karakter/kultura/2026/03/09/t...,[Timothée Chalamet beszólt az operára és balet...,"[„Nem akarok balettben, operában vagy olyan he..."
411,https://telex.hu/after/2026/03/09/majka-lentul...,[Majka a mandineres Lentulai Krisztiánnak: Ado...,[A hétvégi debreceni DPK-gyűlés után Szabó Zsó...
427,https://telex.hu/kulfold/2026/03/09/az-ukran-k...,[Az ukránok bekérették Magyarország nagyköveté...,"[Az , ukrán külügyminisztérium hétfőn bekérett..."
429,https://telex.hu/dokumentum/feliratkozas-hirle...,[],"[A , Diszpó , hírlevélre technikai okok miatt ..."
543,https://telex.hu/dokumentum/altalanos-szerzode...,[],"[Fogalmak., Adatkezelési tájékoztató: a Telex...."
545,https://telex.hu/belfold/2026/03/09/dobrev-kla...,[Dobrev Klára szerint nem sikerült megsemmisít...,[Az ajánlóívek leadásának pénteki határideje ó...
672,https://telex.hu/gazdasag/2026/03/09/olaj-fold...,"[Megteltek az arab tartályok, vezetékek, tanke...","[Most, 8-9 nappal az Irán elleni támadások utá..."
679,https://telex.hu/dokumentum/atlathatosag,[],"[A , Telex működését a támogatóink teszik lehe..."
688,https://telex.hu/gazdasag/2026/03/09/benzinars...,"[Orbán Viktor bejelentette, hogy visszahozzák ...",[Visszavezeti az üzemanyag-árstopot a magyar k...
690,https://telex.hu/g7/podcast/2025/11/17/teherha...,[Hová tűntek a hajók a Dunáról?],[„A magyar hajózás súlya ma két százalék alatt...
705,https://telex.hu/g7/vallalat/2026/03/04/byd-ki...,[Nagyon felértékelődhet a szegedi üzem a BYD-n...,"[A BYD számára, nagyon felértékelődhet a szeg..."
712,https://telex.hu/rovat/kulfold,[],[]
991,https://telex.hu/g7/legfrissebb,[],[]
992,https://telex.hu/g7/podcast/2025/10/04/iskola-...,"[Nemcsak az iskola színvonala fontos, hanem a ...",[Az iskola nemcsak nevelési és oktatási intézm...
1002,https://telex.hu/gazdasag/2026/03/08/mercedes-...,"[Drámaian beesett a profit a Mercedesnél, a cé...",[Az autók iránt érdeklődők többsége elnémul az...
1004,https://telex.hu/g7/elet/2026/03/05/otthon-sta...,[Megszünteti az Otthon Start egy ingatlantípus...,"[Rohamosan zárkóznak fel, a zártkertek árai a..."
1008,https://telex.hu/g7/penz/2026/03/05/energiaimp...,"[Úgy viselkedik a forint, mint a 2022-es energ...","[Kiszámíthatatlanul mozog, a forint az euróva..."
1182,https://telex.hu/g7/tamogatott-tartalom/2025/1...,[Megtanul a magyar e-kereskedelem világszínvon...,[A járvány alatt felpörgő digitalizáció nem ál...
1204,https://telex.hu/karakter/rovat/nagyito,[],[]
1205,https://telex.hu/karakter/rovat/konyvespolc,[],[]
1594,https://telex.hu/karakter/kultura/2025/11/03/a...,[A Magyar Nemzeti Múzeum főigazgatója kapta me...,"[Zsigmond Gábor, a Magyar Nemzeti Múzeum főiga..."

# Transfermarkt spider

In [ ]:
import scrapy
import time 
import sys, json
import socket
import requests
import scrapy
from scrapy.crawler import CrawlerProcess
import datetime

class Transfermarkt(scrapy.Spider):
    custom_settings = {
        "TWISTED_REACTOR": "twisted.internet.epollreactor.EPollReactor",
    }
    name = 'transfermarkt'
    allowed_domains = ['transfermarkt.com']

    def get_club(self, link):
        if link.xpath('.//a'):
            return link.xpath('.//a//text()').extract()
        else:
            return link.xpath('.//text()').extract()

    def start_requests(self):
        start_date = datetime.date(2024, 9, 30)
        end_date = datetime.date.today()
        delta = datetime.timedelta(days=1)
        while start_date <= end_date:
            yield scrapy.Request(url='https://www.transfermarkt.com/transfers/transfertagedetail/statistik/top/plus/0/galerie/0?'\
                                     'land_id_ab=&land_id_zu=&leihe=&datum=' + start_date.strftime('%Y-%m-%d'), callback=self.parse)
            start_date += delta

    def parse(self, response):
        for line in response.xpath('//tr[@class="odd" or @class="even"]'):
            links=line.xpath('.//td[@class="hauptlink"]')
            data = {"name":links[0].xpath('.//a//text()').extract()[0], "left":self.get_club(links[1])[0], "joined":self.get_club(links[2])[0]}
            yield data
        next_page = response.xpath('//li[@class="naechste-seite"]//a/@href').extract()
        if next_page:
            yield scrapy.Request(url='https://transfermarkt.com' + next_page[0], callback=self.parse)

In [ ]:
import os
outfile = 'transfermarkt.json'
if os.path.isfile(outfile):
    os.remove(outfile) 
    
process = CrawlerProcess(settings={
    'LOG_LEVEL': 'WARN',  # Suppress logs
    'FEED_FORMAT': 'json',
    'FEED_URI': outfile,
    'FEED_EXPORT_ENCODING': 'utf-8',
    'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
})
process.crawl(Transfermarkt)

process.start()

2026-03-09 21:37:43 [py.warnings] WARNING: /home/benczur/.local/lib/python3.9/site-packages/scrapy/extensions/feedexport.py:455: ScrapyDeprecationWarning: The `FEED_URI` and `FEED_FORMAT` settings have been deprecated in favor of the `FEEDS` setting. Please see the `FEEDS` setting docs for more details
  exporter = cls(crawler)

2026-03-09 21:37:43 [py.warnings] WARNING: /home/benczur/.local/lib/python3.9/site-packages/scrapy/core/spidermw.py:433: ScrapyDeprecationWarning: __main__.Transfermarkt defines the deprecated start_requests() method. start_requests() has been deprecated in favor of a new method, start(), to support asynchronous code execution. start_requests() will stop being called in a future version of Scrapy. If you use Scrapy 2.13 or higher only, replace start_requests() with start(); note that start() is a coroutine (async def). If you need to maintain compatibility with lower Scrapy versions, when overriding start_requests() in a spider class, override start() as well; you can use super() to reuse the inherited start() implementation without copy-pasting. See the release notes of Scrapy 2.13 for details: https://docs.scrapy.org/en/2.13/news.html
  warn(

In [ ]:
import pandas as pd
transferdata=pd.read_json(outfile)
transferdata

RuntimeError: module was compiled against NumPy C-API version 0x10 (NumPy 1.23) but the running NumPy has C-API version 0xf. Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem.

                     name             left           joined
0         Sofiane Boudraa  Valenciennes FC  Aubagne Air Bel
1              Abdo Gouda      Pyramids FC    Harras Hodoud
2             Corry Evans     Without Club         Bradford
3             Seidu Basit         Al-Hilal      Fujairah SC
4           Gabriel Torje        Concordia        Campulung
...                   ...              ...              ...
10547             Yubo Hu        HM Codion  LZ Longyuan At.
10548    Andrius Kaulinis         Riteriai        Hegelmann
10549  Vladislav Ignatjev     BATE Borisov    Dnepr Mogilev
10550       Håvar Jenssen     Sarpsborg 08             KFUM
10551    Jonathan Muzinga         FC Lahti              VPS

[10552 rows x 3 columns]